config/routes.rb
RedditClone::Application.routes.draw do
  root to: "subs#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]

  resources :subs, except: [:destroy]
  
  resources :posts, only: [:new, :create, :show] do
  	resources :comments, only: [:new, :create, :show]
  end
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string(255)      not null
#  moderator_id :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Sub < ActiveRecord::Base
	validates :title, :moderator, presence: true

	has_many :post_subs, inverse_of: :sub, dependent: :destroy

	has_many :posts, through: :post_subs, source: :post
	
	belongs_to :moderator, 
	class_name: "User", 
	foreign_key: :moderator_id,
	primary_key: :id, 
	inverse_of: :subs
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
	before_action :require_signed_in
	before_action :user_owns_sub?, only: [:edit, :update]

	def index
		@subs = Sub.all
		render :index
	end

	def new
		@sub = Sub.new
		5.times {@sub.posts.new}

		render :new
	end

	def show
		@sub = Sub.find(params[:id])
		# @moderator = User.find(@sub.moderator_id)
		render :show
	end

	def create
		@sub = current_user.subs.new(sub_params)
		filled_out_posts = params[:posts].values.reject do |value|
      		value[:url].empty? || value[:title].empty?
    	end

    	filled_out_posts.each do |post_params|
      		@sub.posts.new(post_params.merge(user_id: current_user.id))
    	end

		if @sub.save
			redirect_to sub_url(@sub)
		else
			flash.now[:errors] = @sub.errors.full_messages
			render :new
		end
	end

	def edit
		@sub = Sub.find(params[:id])
		render :edit
	end

	def update
		@sub = Sub.find(params[:id])

		if @sub.update_attributes(sub_params)
			redirect_to sub_url(@sub)
		else
			flash.now[:errors] = @sub.errors.full_messages
			render :edit
		end
	end

	private

	def user_owns_sub?
		@sub = Sub.find(params[:id])
    	redirect_to sub_url(@sub) unless @sub.moderator == current_user
  	end

	def sub_params
		params.require(:sub).permit(:title, :moderator_id)
	end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<% if new_sub %>
  <% action_url = subs_url %>
<% else %>
  <% action_url = sub_url(sub) %>
<% end %>

<form action="<%= action_url %>" method="POST">
  Sub Title: <input name="sub[title]" value="<%= sub.title %>"><br>

  <% if new_sub %>
    <h2>Submit up to 5 posts!</h2>

    <% sub.posts.each.with_index do |post, index| %>
      URL: <input name="posts[<%= index %>][url]" value="<%= post.url %>"><br>
      Title: <input name="posts[<%= index %>][title]" value="<%= post.title %>"><br>
      Content: <input name="posts[<%= index %>][content]" value="<%= post.content %>"><br><br>
    <% end %>

  <% else %>
      <input type="hidden" name="_method" value="PUT">
  <% end %>
    <input type="submit" value="Submit">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

app/views/subs/edit.html.erb
<h1>Edit <%= @sub.title %></h1>


	<form action="<%= sub_url(@sub) %>" method="POST">
		<input type="hidden" name="_method" value="PATCH">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

		<label>Title
			<input type="text" 
			name="sub[title]" 
			value="<%= @sub.title %>">
		</label>
		<br><br>
		
		<input type="hidden" 
		name="sub[moderator_id]" 
		value="<%= @sub.moderator_id %>">

		<input type="submit" value="Edit Sub">
	</form>

app/views/subs/index.html.erb
<h3>Subreddits</h3>

<% @subs.each do |sub| %>
  <%= link_to sub.title, sub %><br>
<% end %>

<br><br>
<%= link_to "Add A Subreddit", new_sub_url %>

app/views/subs/new.html.erb
<h1>Create a new sub!</h1>
<%= render "form", sub: @sub, new_sub: true %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<% if current_user == @sub.moderator %>
	<%= link_to "Edit Your Sub", edit_sub_url(@sub) %><br>
<% end %>

<h3>Posts</h3>
<ul>
	<% @sub.posts.each do |post| %>
	  <li><%= link_to post.title, post %></li>
	<% end %>
</ul>

<p>
	<% if current_user == @sub.moderator %>
		<em>moderated by yourself</em>
	<% else %>
		<em>moderator: <%= @sub.moderator.username %></em>
	<% end %>
</p>

<br>

<%= link_to "Submit a New Post", new_post_url %><br>
<%= link_to "Back to SubReddits", subs_url %>