config/routes.rb
RedditClone::Application.routes.draw do
  root to: "subs#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]

  resources :subs, except: [:destroy]
  
  resources :posts, only: [:new, :create, :show] do
  	resources :comments, only: [:new, :create, :show]
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  url        :string(255)      not null
#  content    :string(255)      not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
	validates :title, :url, :content, :user, presence: true

	belongs_to :user, inverse_of: :posts

	has_many :post_subs, 
	class_name: "PostSub",
	foreign_key: :post_id, 
	primary_key: :id, 
	inverse_of: :post, 
	dependent: :destroy

	has_many :subs, through: :post_subs, source: :sub

	has_many :comments, inverse_of: :post

	has_many :votes, as: :votable

	def comments_by_parent
		comments_by_parent = Hash.new {|hash, key| hash[key] = []}

		comments.each do |comment|
			comments_by_parent[comment.parent_comment_id] << comment
		end

		comments_by_parent
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :require_signed_in

	def new
		@subs = Sub.all
		@post = Post.new
		render :new
	end

	def show
		@post = Post.find(params[:id])
		render :show
	end

	def create
		@post = current_user.posts.new(post_params)
		if @post.save
			redirect_to post_url(@post)
		else
			flash.now[:errors] = @post.errors.full_messages
			@subs = Sub.all
			render :new
		end
	end

	def edit
    	@subs = Sub.all
  	end

  	def update
  		if @post.update_attributes(post_params)
  			redirect_to post_url(@post)
  		else
  			flash.now[:errors] = @post.errors.full_messages
      		render :edit
  		end
  	end

	private
	def post_params
		params.require(:post).permit(:title, :url, :content, {sub_ids: []}, :user_id)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<form action="<%= post_comments_url(@post) %>" method="POST">
  <input type="hidden" name="authenticity_token" id="" value="<%= form_authenticity_token %>" />
  <textarea name="comment[content]" placeholder="<%= message %>"></textarea><br>
  <input type="submit">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="hidden" name="comment[parent_comment_id]" value="<%= parent_comment_id %>">
</form>

app/views/posts/_form.html.erb
<% if new_post %>
  <% action_url = posts_url %>
<% else %>
  <% action_url = post_url(post) %>
<% end %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  URL: <input name="post[url]" value="<%= post.url %>"><br>
  Title: <input name="post[title]" value="<%= post.title %>"><br>
  Body: <input name="post[content]" value="<%= post.content %>"><br><br>

  <% subs.each do |sub| %>
    <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked".html_safe if post.sub_ids.include?(sub.id) %>>
    <%= sub.title %><br>
  <% end %>

  <% unless new_post %>
    <input type="hidden" name="_method" value="PUT">
  <% end %>

  <input type="Submit" value="Create Post">
</form>

app/views/posts/edit.html.erb
<h1>Edit your Sub</h1>

<%= render "form", sub: @sub, new_sub: false %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post, new_post: true, subs: @subs %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<a href="http://<%= @post.url %>">
<%= @post.content %></a><br>
<em>submitted by <%= User.find(@post.user_id).username %></em>
<br><br>

<%= render "comment", parent_comment_id: nil, message: "What do you think?" %>

<h3>Comments on <%= @post.title %></h3>
<ul>
  <% comments_by_parent = @post.comments_by_parent %>
  <% comments_by_parent[nil].each do |parent_comment| %>
    <li>
    <%= comment_partial(parent_comment, comments_by_parent) %>
    </li>
  <% end %>
</ul>

<br>
<%= link_to "Back to Subs", subs_url%>